
Settings.insert =
  abbreviations:
    "archive": "arXiv"
    'avenue': 'Ave.'
    "at all": "et al."
    "background": "bkgnd"
    "bio archive": "bioRxiv"
    "bowtie": "bwt"
    "bullion": "bool"
    "boolean": "bool"
    "cufflinks": "cuff"
    "device": "dev"
    "dimension": "dim"
    "dispersion": "disp"
    "emphasis": "emph"
    "ensemble": "ensembl"
    "express": "xprs"
    "expression": "exprs"
    "professor": "Prof."
    "phd": "PhD"
    'doctor': 'Dr.'
    "Company": "Co."
    "control": "ctrl"
    "kallisto": "kal"
    "knitter": "knitr"
    "index": "idx"
    "in example": "i.e."
    "jpeg": "jpg"
    "dictionary": "dict"
    'example given': 'e.g.'
    "infinite": "Inf"
    "linter": "lintr"
    "markdown": "md"
    'message': 'msg'
    "miscellaneous": "misc"
    "mount": "mnt"
    "option": "opt"
    "package": "pkg"
    'password': 'passwd'
    "plot": "plt"
    "poisson": "pois"
    "pritchard": "pritch"
    "python": "py"
    "regular expression": "regex"
    "repeat": "rep"
    "return": "ret"
    "screen": "scr"
    "serial": "ser"
    "simulations": "sims"
    "simulation": "sim"
    "connection": "con"
    "current": "cur"
    "latex": "tex"
    "matrix": "mat"
    "national science foundation": "NSF"
    "national institute of health": "NIH"
    'numpy': 'np'
    "penn": "pen"
    "section": "sec"
    "sequence": "seq"
    "separator": "sep"
    "server": "srv"
    "snip": "snp"
    "substitute": "sub"
    'transcript import': 'tximport'
    "trademark": "(tm)"
    user: "usr"
    uniform: 'unif'
    "exponent": "exp"
    "square root": "sqrt"
    "directories": "dirs"
    "volcano": "vol"
    # these help with R
    "absolute": "abs"
    "aesthetic": "aes"
    "correlation": "cor"
    "covariance": "cov"
    "diagonal": "diag"
    "empirical distribution": "ecdf"
    "geometry": "geom"
    "some": "sum"
    "statistic": "stat"
    "limit": "lim"
    "observed": "obs"
    "observation": "obs"
    "points": "pnts"
    "probability": "prob"
    "probabilities": "probs"
