Settings.web =
  websites:
    "amazon": "https://amazon.com"
    "atom": "https://atom.io/docs"
    "atom discuss": "https://discuss.atom.io/"
    "atom package": "https://atom.io/packages"
    "atom packages": "https://atom.io/packages"
    "bit bucket": "https://bitbucket.org/"
    "bears": "https://github.com/pachterlab/bears_analyses"
    "calendar": "https://calendar.google.com"
    "drive": "https://drive.google.com"
    "facebook": "https://facebook.com"
    "face": "https://facebook.com"
    "get": "https://github.com/"
    'github': "https://github.com/"
    'gmail': 'https://mail.google.com'
    "kallisto": "https://github.com/pachterlab/kallisto"
    "patch": "https://github.com/pachterlab"
    "pimentel": "https://pimentel.github.io/"
    "read it": "https://www.reddit.com/"
    "scholar": "https://scholar.google.com/"
    "sleuth": "https://github.com/pachterlab/sleuth"
    "trello": "https://trello.com/"
    "twitter": "https://twitter.com"
    'voice': 'http://voicecode.io/docs'
    "whether": "http://www.weather.com/weather/hourbyhour/l/94402"
    "yelp": "https://yelp.com"
